data = {
    school: "General Assembly",
    city: "San Francisco",
    course: "Web Development Immersive",
    course_id: "WDI24",
    classrootm: "7",
    students: [{
        id: 0,
        last_name: "Abeyta",
        first_name: "Adam",
        github_username: "abeytaadam"
    }, {
        id: 1,
        last_name: "Lee",
        first_name: "Alan",
        github_username: "alanlee35"
    }, {
        id: 2,
        last_name: "Massey",
        first_name: "Andre",
        github_username: "DreTGiant"
    }, {
        id: 0,
        last_name: "Saavedra",
        first_name: "Carlos",
        github_username: "murcielago17"
    }, {
        id: 1,
        last_name: "Salinas",
        first_name: "Cynthia",
        github_username: "Cyndy528"
    }, {
        id: 2,
        last_name: "Sloan",
        first_name: "Dave",
        github_username: "slnwlf"
    }, {
        id: 0,
        last_name: "Chang",
        first_name: "Eddy",
        github_username: "TheEddyChang"
    }, {
        id: 1,
        last_name: "Dwyer",
        first_name: "John",
        github_username: "Jsdwyer26"
    }, {
        id: 2,
        last_name: "Rockway",
        first_name: "Michael",
        github_username: "mrockway"
    }, {
        id: 0,
        last_name: "Stevens",
        first_name: "Stanley",
        github_username: "Stanleyyork"
    }, {
        id: 1,
        last_name: "Noble",
        first_name: "Steven",
        github_username: "stevennoble78"
    }, {
        id: 2,
        last_name: "Huynh",
        first_name: "Trung",
        github_username: "tkhuynh"
    }, {
        id: 0,
        last_name: "Frambach",
        first_name: "Victoria",
        github_username: "vframbach"
    }, {
        id: 1,
        last_name: "Muzafi",
        first_name: "Zohar",
        github_username: "zoharmuzafi"
    }]
}
